name: DEV STAGING
on:
  push:
    branches:
      - 'feature'
  
jobs:

  SnykSecurity:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - name: Run Snyk to check Scala
        uses: snyk/actions/scala@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
        with:
          args: --all-projects --severity-threshold=critical
        
  GitLeaks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - name: Check for GitLeaks
        uses: gacts/gitleaks@v1 
        if: always()
        
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  Run-Ansible-Locally:
      needs: [SnykSecurity, SonarCloud]
      runs-on: [self-hosted, lila-dev]
      steps:
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yaml
          directory: /home/dodo/lila-project/
          options: --vault-pass-file /home/dodo/pass
          
