name: CI to DockerHub

on:
  push:
    branches: "*"
    paths:
      - '*/Dockerfile'
jobs:
  build:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mongo/
          file: ./mongo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:mongo1
      -
        name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/dodo1845/dodohub:mongo1'
          format: 'sarif'
          output: 'trivy-results.sarif'
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      -
        name: Run MONGO
        run: docker run -d -p 27017:27017 dodo1845/dodohub:0.66
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./redis/
          file: ./redis/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:redis1
      -
        name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/dodo1845/dodohub:redis1'
          format: 'sarif'
          output: 'trivy-results.sarif'
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./lila/
          file: ./lila/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:lila1
      -
        name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/dodo1845/dodohub:lila1'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
