name: CI to DockerHub

on:
  push:
    branches: "*"
    paths:
      - '*/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mongo/
          file: ./mongo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:latest
      -
        name: Run MONGO
        run: docker run -d -p 27017:27017 dodo1845/dodohub:0.66
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./redis/
          file: ./redis/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./lila/
          file: ./lila/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dodohub:latest
      
