name: SBT ScalaFMT check
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Check formatting with scalafmt
      uses: olafurpg/setup-scala@v11
      with:
        java-version: 11
        sbt-version: 1.5.5
    - name: Run scalafmt
      run: sbt "scalafmt --config .scalafmt.conf --test"
      working-directory: lila/lila
